version: '3'
services:
  psql-container:
    image: postgres
    container_name: psql-container
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ubuntu
      POSTGRES_DB: yelp
    ports:
      - "5432:5432"
  
  redis-container:
    image: redis
    container_name: redis-container
    restart: always
    networks:
      - my-network
    ports:
      - "6379:6379"

  backend-container:
    # build:
    #   context: ./server
    image: public.ecr.aws/t9w2k7r1/mybackend:1.0
    container_name: backend-container
    restart: always
    networks:
      - my-network
    # env_file:
    #   - ./server/.env
    environment:
      NODE_ENV: production
      SESSION_SECRET: keyboard
      PORT: 4000
      USERNAME: "ubuntu"
      PASSWORD: "password"
      DATABASE: "yelp"
      DATABASE_PORT: 5432
    ports:
      - "4000:4000"

  frontend-container:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile
    image: public.ecr.aws/t9w2k7r1/myfrontend:1.0
    container_name: frontend-container
    restart: always
    networks:
      - my-network
    environment:
      NODE_ENV: production
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:5173"

networks:
  my-network:
    driver: bridge
